version: 2.1
orbs:
  gcp-gcr: circleci/gcp-gcr@0.6.1
jobs:
  full_build:
    machine:
      docker_layer_caching: true
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /tmp/key.json
    steps:
      - checkout
      - run:
          name: "gcloud auth"
          command: |
            echo $ENCODED_GCR_KEY | base64 -d > $GOOGLE_APPLICATION_CREDENTIALS 
      - run:
          name: "Pull Submodules"
          command: |
            git submodule update --init --recursive
      - run: 
          name: "Build containers, run tests"
          command: |
            PULL=False make tests
  just_run_tests:
    machine:
      docker_layer_caching: true
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /tmp/key.json
    steps:
      - checkout
      - run:
          name: "gcloud auth"
          command: |
            echo $ENCODED_GCR_KEY | base64 -d > $GOOGLE_APPLICATION_CREDENTIALS
      - gcp-gcr/gcr-auth
      - run: 
          name: "Run tests"
          command: |
	    echo "$ENCODED_GCR_KEY" | base64 --decode | docker login --username _json_key --password-stdin https://gcr.io
            make tests
     
workflows:
  version: 2
  build:
    jobs:
      - just_run_tests:
          filters:
            branches:
              only:
                - master