version: 2.1
orbs:
  gcp-gcr: circleci/gcp-gcr@0.6.1
jobs:
  lint:
    docker:
    - image: circleci/python:3.7
    steps:
      - checkout
      - run: sudo pip3 install black==19.10b0 flake8==3.7.8
      - run: make lint
  full_build:
    machine:
      docker_layer_caching: false
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /tmp/key.json
      BUILD_IMAGE: us.gcr.io/vcm-ml/fv3ser-install:latest
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "80:d3:ce:22:ea:9e:bf:df:1c:8d:64:e2:c1:8e:2c:44"
      - run:
          name: "gcloud auth"
          command: |
            echo $ENCODED_GCR_KEY | base64 -d > $GOOGLE_APPLICATION_CREDENTIALS
      - run:
          name: "Pull Submodules"
          command: |
            git submodule update --init --recursive
      - gcp-gcr/gcr-auth
      - run:
          name: "Build containers, run tests"
          command: |
            PULL=False make tests

      - run:
          name: "Push new image"
          command: |
            docker push $BUILD_IMAGE
  just_run_tests:
    machine:
      docker_layer_caching: true
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /tmp/key.json
      BUILD_IMAGE: us.gcr.io/vcm-ml/fv3ser-install:latest
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "80:d3:ce:22:ea:9e:bf:df:1c:8d:64:e2:c1:8e:2c:44"
      - run:
          name: "gcloud auth"
          command: |
            echo $ENCODED_GCR_KEY | base64 -d > $GOOGLE_APPLICATION_CREDENTIALS
      - run:
          name: "Pull Submodules"
          command: |
            git submodule update --init --recursive
      - gcp-gcr/gcr-auth
      - run:
          name: "Pull environment image"
	  command: |
	    docker pull $BUILD_IMAGE
      - run:
          name: "Run tests"
          command: |
            make tests
      - run:
          name: "Run parallel tests"
          command: |
            make tests_mpi
  just_run_dawn_tests:
    machine:
      docker_layer_caching: true
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /tmp/key.json
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "80:d3:ce:22:ea:9e:bf:df:1c:8d:64:e2:c1:8e:2c:44"
      - run:
          name: "Pull Submodules"
          command: |
            git submodule update --init --recursive
      - run:
          name: "gcloud auth"
          command: |
            echo $ENCODED_GCR_KEY | base64 -d > $GOOGLE_APPLICATION_CREDENTIALS
      - gcp-gcr/gcr-auth
      - run:
          name: "Run tests"
          command: |
            TEST_ARGS="--backend=dawn:gtmc -v -s -rsx" make tests

workflows:
  version: 2
  build:
    jobs:
      - lint
      - just_run_tests
  nightly_build:
    triggers:
      - schedule:
          cron: "0 7 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - full_build
  nightly_dawn_tests:
    triggers:
      - schedule:
          cron: "0 9 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - just_run_dawn_tests
